/**
 * Generate a human-readable hook registry doc.
 *
 * Output: dist/hook-registry.md
 *
 * Lists the v2 catalog (18 events across Class A / B / D) with their
 * blocking semantics, allowed outcome fields, payload-schema reference
 * and redaction hints. This is the governance-team artefact backing the
 * in-scope allowlist truth.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  HOOK_EVENT_CATALOG,
  ASYNC_COMPACT_HOOK_EVENTS,
  CLASS_B_HOOK_EVENTS,
} from "../src/catalog.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "dist");
mkdirSync(outDir, { recursive: true });

const CLASS_A = new Set([
  "SessionStart",
  "SessionEnd",
  "UserPromptSubmit",
  "PreToolUse",
  "PostToolUse",
  "PostToolUseFailure",
  "PreCompact",
  "PostCompact",
]);
const CLASS_B = new Set(CLASS_B_HOOK_EVENTS);
const CLASS_D = new Set([
  ...ASYNC_COMPACT_HOOK_EVENTS,
  "EvalSinkOverflow",
]);

function classOf(name: string): string {
  if (CLASS_A.has(name)) return "A";
  if (CLASS_B.has(name as never)) return "B";
  if (CLASS_D.has(name as never)) return "D";
  return "?";
}

const lines: string[] = [];
lines.push("# Hook Registry — @nano-agent/hooks (v2 — 18 events)");
lines.push("");
lines.push("_This file is auto-generated by `scripts/gen-registry-doc.ts`._");
lines.push("");
lines.push(`Total events: **${Object.keys(HOOK_EVENT_CATALOG).length}**`);
lines.push("");
lines.push("- Class A (8) — unchanged from the 1.x baseline.");
lines.push("- Class B (4) — Setup / Stop / PermissionRequest / PermissionDenied.");
lines.push("- Class D (6) — ContextPressure + 4 async-compact lifecycle events + EvalSinkOverflow.");
lines.push("");
lines.push("## 1. Event catalog");
lines.push("");
lines.push("| Event | Class | Blocking | Allowed outcomes | Redaction hints | Payload schema |");
lines.push("|-------|-------|----------|------------------|------------------|----------------|");
for (const [name, meta] of Object.entries(HOOK_EVENT_CATALOG)) {
  lines.push(
    `| \`${name}\` | ${classOf(name)} | ${meta.blocking ? "yes" : "no"} | ${meta.allowedOutcomes.map((o) => `\`${o}\``).join(", ")} | ${meta.redactionHints.length ? meta.redactionHints.map((h) => `\`${h}\``).join(", ") : "—"} | \`${meta.payloadSchema}\` |`,
  );
}
lines.push("");
lines.push("## 2. Source priority (lookup order)");
lines.push("");
lines.push("`platform-policy` > `session` > `skill`");
lines.push("");
lines.push("## 3. Runtime kinds");
lines.push("");
lines.push("- `local-ts` — trusted in-proc TypeScript handler");
lines.push("- `service-binding` — remote hook worker via NACP-Core (stub in v1)");
lines.push("");
lines.push("## 4. Limitations & wire-truth notes");
lines.push("");
lines.push("- `updatedInput` is only valid on `PreToolUse`.");
lines.push("- `stop` is only valid on `PostToolUseFailure`.");
lines.push("- Matchers: `exact` / `wildcard` / `toolName` only (no regex).");
lines.push("- Client is receive-only on `hook.broadcast` — clients cannot respond with a `HookOutcome`.");
lines.push("- `PermissionRequest` wire truth (B5 §2.3 override of P4 §8.5):");
lines.push("  - `continue` ⇒ verdict = **allow**.");
lines.push("  - `block { reason }` ⇒ verdict = **deny**.");
lines.push("  - Zero registered handlers ⇒ **fail-closed deny** (caller's responsibility).");
lines.push("  - The `allow` / `deny` vocabulary is package-local only (see `permission.ts::verdictOf()`);");
lines.push("    the nacp-core wire body is NOT extended.");
lines.push("- `EvalSinkOverflow`: metadata only in B5; producer ships in B6 (eval-observability dedup patch).");

const outPath = join(outDir, "hook-registry.md");
writeFileSync(outPath, lines.join("\n"));
console.log(`✅ Generated hook registry doc → ${outPath}`);
