/**
 * Generate a human-readable storage placement doc.
 *
 * Output: dist/storage-placement.md
 *
 * Renders the full placement hypothesis table, checkpoint-candidate
 * fragments, and the archive / promotion / demotion plan trigger maps
 * so reviewers can see at a glance:
 *   - where each data item lives today
 *   - which are frozen vs still provisional
 *   - which runtime owns each field / plan
 *   - what evidence would revisit the decision
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { DATA_ITEM_CATALOG } from "../src/data-items.js";
import { PLACEMENT_HYPOTHESES } from "../src/placement.js";
import {
  CHECKPOINT_CANDIDATE_FIELDS,
  summarizeFragments,
} from "../src/checkpoint-candidate.js";
import { ARCHIVE_PLANS } from "../src/archive-plan.js";
import { PROMOTION_PLANS } from "../src/promotion-plan.js";
import { DEMOTION_PLANS } from "../src/demotion-plan.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "dist");
mkdirSync(outDir, { recursive: true });

const lines: string[] = [];
lines.push("# Storage Placement — @nano-agent/storage-topology");
lines.push("");
lines.push("_This file is auto-generated by `scripts/gen-placement-doc.ts`._");
lines.push("");

lines.push("## 1. Placement hypotheses");
lines.push("");
lines.push("| Data item | Backend | Provisional | Revisit condition | Rationale |");
lines.push("|-----------|---------|-------------|-------------------|-----------|");
for (const [item, p] of PLACEMENT_HYPOTHESES) {
  const catalog = DATA_ITEM_CATALOG[item];
  lines.push(
    `| \`${item}\` | \`${p.storageBackend}\` | ${p.provisional} | ${p.revisitCondition} | ${catalog?.displayName ?? ""} |`,
  );
}
lines.push("");

lines.push("## 2. Checkpoint fragment boundaries");
lines.push("");
const summary = summarizeFragments();
lines.push("| Fragment | Fields | Description |");
lines.push("|----------|--------|-------------|");
lines.push(`| kernel | ${summary.kernel} | Agent runtime snapshot + tool in-flight state |`);
lines.push(`| session | ${summary.session} | nacp-session replay / stream seqs / audit trail segment |`);
lines.push(`| workspace | ${summary.workspace} | Delegated to @nano-agent/workspace-context-artifacts |`);
lines.push(`| hooks | ${summary.hooks} | Session hook registry snapshot |`);
lines.push(`| usage | ${summary.usage} | Session-level usage counters |`);
lines.push("");

lines.push("## 3. Checkpoint candidate fields");
lines.push("");
lines.push("| Field | Fragment | Owner | Provisional | Pending questions |");
lines.push("|-------|----------|-------|-------------|-------------------|");
for (const f of CHECKPOINT_CANDIDATE_FIELDS) {
  lines.push(
    `| \`${f.fieldName}\` | ${f.fragment} | ${f.ownerRuntime} | ${f.provisional} | ${
      f.pendingQuestions.length === 0 ? "—" : f.pendingQuestions.map((q) => `• ${q}`).join("<br>")
    } |`,
  );
}
lines.push("");

lines.push("## 4. Archive / promotion / demotion plans");
lines.push("");
lines.push("### Archive (→ cold)");
lines.push("");
lines.push("| Trigger | Source → Target | Responsible runtime |");
lines.push("|---------|-----------------|--------------------|");
for (const p of ARCHIVE_PLANS) {
  lines.push(`| ${p.trigger} | ${p.sourceBackend} → ${p.targetBackend} | ${p.responsibleRuntime} |`);
}
lines.push("");

lines.push("### Promotion (→ hot)");
lines.push("");
lines.push("| Trigger | From → To |");
lines.push("|---------|-----------|");
for (const p of PROMOTION_PLANS) lines.push(`| ${p.trigger} | ${p.from} → ${p.to} |`);
lines.push("");

lines.push("### Demotion");
lines.push("");
lines.push("| Trigger | From → To |");
lines.push("|---------|-----------|");
for (const d of DEMOTION_PLANS) lines.push(`| ${d.trigger} | ${d.from} → ${d.to} |`);
lines.push("");

const outPath = join(outDir, "storage-placement.md");
writeFileSync(outPath, lines.join("\n"));
console.log(`✅ Generated storage placement doc → ${outPath}`);
