// Auto-generated by packages/nacp-core/scripts/generate-error-registry-client-data.ts.
// DO NOT EDIT BY HAND.

import type { ClientErrorMeta } from "./types.js";

export const GENERATED_CLIENT_ERROR_META = [
  {
    "code": "invalid-request",
    "category": "validation.failed",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "invalid-input",
    "category": "validation.failed",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "invalid-meta",
    "category": "validation.failed",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "invalid-trace",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "invalid-authority",
    "category": "auth.expired",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "invalid-caller",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "invalid-session",
    "category": "request.error",
    "http_status": 404,
    "retryable": false
  },
  {
    "code": "invalid-auth",
    "category": "auth.expired",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "identity-already-exists",
    "category": "conflict.state",
    "http_status": 409,
    "retryable": false
  },
  {
    "code": "identity-not-found",
    "category": "request.error",
    "http_status": 404,
    "retryable": false
  },
  {
    "code": "password-mismatch",
    "category": "auth.expired",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "refresh-invalid",
    "category": "auth.expired",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "refresh-expired",
    "category": "auth.expired",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "refresh-revoked",
    "category": "auth.expired",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "invalid-wechat-code",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "invalid-wechat-payload",
    "category": "dependency.unavailable",
    "http_status": 502,
    "retryable": true
  },
  {
    "code": "permission-denied",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "binding-scope-forbidden",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "tenant-mismatch",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "authority-escalation",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "not-found",
    "category": "request.error",
    "http_status": 404,
    "retryable": false
  },
  {
    "code": "conflict",
    "category": "conflict.state",
    "http_status": 409,
    "retryable": false
  },
  {
    "code": "session-not-running",
    "category": "conflict.state",
    "http_status": 409,
    "retryable": false
  },
  {
    "code": "session-already-ended",
    "category": "conflict.state",
    "http_status": 410,
    "retryable": false
  },
  {
    "code": "worker-misconfigured",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "rpc-parity-failed",
    "category": "dependency.unavailable",
    "http_status": 500,
    "retryable": true
  },
  {
    "code": "upstream-timeout",
    "category": "dependency.unavailable",
    "http_status": 504,
    "retryable": true
  },
  {
    "code": "rate-limited",
    "category": "quota.exceeded",
    "http_status": 429,
    "retryable": true
  },
  {
    "code": "not-supported",
    "category": "request.error",
    "http_status": 501,
    "retryable": false
  },
  {
    "code": "internal-error",
    "category": "dependency.unavailable",
    "http_status": 500,
    "retryable": true
  },
  {
    "code": "NACP_VALIDATION_FAILED",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "NACP_UNKNOWN_MESSAGE_TYPE",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "NACP_SIZE_EXCEEDED",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "NACP_VERSION_INCOMPATIBLE",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "NACP_TYPE_DIRECTION_MISMATCH",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "NACP_DEADLINE_EXCEEDED",
    "category": "dependency.unavailable",
    "http_status": 503,
    "retryable": false
  },
  {
    "code": "NACP_IDEMPOTENCY_CONFLICT",
    "category": "conflict.state",
    "http_status": 409,
    "retryable": false
  },
  {
    "code": "NACP_CAPABILITY_DENIED",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_RATE_LIMITED",
    "category": "quota.exceeded",
    "http_status": 429,
    "retryable": true
  },
  {
    "code": "NACP_BINDING_UNAVAILABLE",
    "category": "dependency.unavailable",
    "http_status": 503,
    "retryable": true
  },
  {
    "code": "NACP_HMAC_INVALID",
    "category": "auth.expired",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_TIMESTAMP_SKEW",
    "category": "auth.expired",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_TENANT_MISMATCH",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_TENANT_BOUNDARY_VIOLATION",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_TENANT_QUOTA_EXCEEDED",
    "category": "quota.exceeded",
    "http_status": 429,
    "retryable": true
  },
  {
    "code": "NACP_DELEGATION_INVALID",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_STATE_MACHINE_VIOLATION",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "NACP_REPLY_TO_CLOSED",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "NACP_PRODUCER_ROLE_MISMATCH",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_REPLAY_OUT_OF_RANGE",
    "category": "runtime.error",
    "http_status": 410,
    "retryable": false
  },
  {
    "code": "ILLEGAL_PHASE_TRANSITION",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "TURN_ALREADY_ACTIVE",
    "category": "conflict.state",
    "http_status": 409,
    "retryable": false
  },
  {
    "code": "TURN_NOT_FOUND",
    "category": "request.error",
    "http_status": 404,
    "retryable": false
  },
  {
    "code": "STEP_TIMEOUT",
    "category": "dependency.unavailable",
    "http_status": 504,
    "retryable": true
  },
  {
    "code": "KERNEL_INTERRUPTED",
    "category": "dependency.unavailable",
    "http_status": 503,
    "retryable": true
  },
  {
    "code": "CHECKPOINT_VERSION_MISMATCH",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "NACP_SESSION_INVALID_PHASE",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "NACP_SESSION_AUTHORITY_REQUIRED",
    "category": "security.denied",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "NACP_SESSION_FORGED_AUTHORITY",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "NACP_SESSION_ACK_MISMATCH",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "NACP_SESSION_HEARTBEAT_TIMEOUT",
    "category": "dependency.unavailable",
    "http_status": 503,
    "retryable": true
  },
  {
    "code": "NACP_SESSION_ALREADY_ATTACHED",
    "category": "conflict.state",
    "http_status": 409,
    "retryable": false
  },
  {
    "code": "NACP_SESSION_TYPE_DIRECTION_MISMATCH",
    "category": "runtime.error",
    "http_status": 500,
    "retryable": false
  },
  {
    "code": "llm-auth",
    "category": "security.denied",
    "http_status": 401,
    "retryable": false
  },
  {
    "code": "llm-rate-limit",
    "category": "quota.exceeded",
    "http_status": 429,
    "retryable": true
  },
  {
    "code": "llm-context-window",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "llm-content-policy",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "llm-bad-request",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "llm-service-unavailable",
    "category": "dependency.unavailable",
    "http_status": 503,
    "retryable": true
  },
  {
    "code": "llm-timeout",
    "category": "dependency.unavailable",
    "http_status": 504,
    "retryable": true
  },
  {
    "code": "llm-other",
    "category": "dependency.unavailable",
    "http_status": 500,
    "retryable": true
  },
  {
    "code": "empty-command",
    "category": "request.error",
    "http_status": 400,
    "retryable": false
  },
  {
    "code": "policy-denied",
    "category": "security.denied",
    "http_status": 403,
    "retryable": false
  },
  {
    "code": "session-not-found",
    "category": "request.error",
    "http_status": 404,
    "retryable": false
  },
  {
    "code": "execution-timeout",
    "category": "dependency.unavailable",
    "http_status": 504,
    "retryable": true
  },
  {
    "code": "execution-failed",
    "category": "dependency.unavailable",
    "http_status": 500,
    "retryable": true
  },
  {
    "code": "bridge-not-found",
    "category": "request.error",
    "http_status": 404,
    "retryable": false
  },
  {
    "code": "handler-error",
    "category": "dependency.unavailable",
    "http_status": 500,
    "retryable": true
  }
] as const satisfies readonly ClientErrorMeta[];
