/**
 * Generate NACP-Core Registry documentation as Markdown.
 * Usage: pnpm -F @nano-agent/nacp-core build:docs
 * Output: stdout (pipe to file)
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Import to trigger registration
import "../src/messages/index.js";

import { NACP_MESSAGE_TYPES_ALL, BODY_REQUIRED, ROLE_GATE } from "../src/envelope.js";
import { listErrorDefinitions } from "../src/error-registry.js";
import { NACP_ROLE_REQUIREMENTS } from "../src/state-machine.js";
import { NACP_VERSION } from "../src/version.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const lines: string[] = [];

lines.push(`# NACP-Core Registry — v${NACP_VERSION}`);
lines.push("");
lines.push("> Auto-generated by \`pnpm build:docs\`. Do not edit manually.");
lines.push("");

// ── Message Types ──
lines.push("## Message Types");
lines.push("");
lines.push("| message_type | body_required | allowed_producer_roles |");
lines.push("|---|---|---|");
for (const mt of [...NACP_MESSAGE_TYPES_ALL].sort()) {
  const req = BODY_REQUIRED.has(mt) ? "✅" : "—";
  const roles = ROLE_GATE[mt] ? [...ROLE_GATE[mt]].join(", ") : "_any_";
  lines.push(`| \`${mt}\` | ${req} | ${roles} |`);
}
lines.push("");

// ── Role Requirements (Core-only) ──
// R3 fix: separate session.* placeholders from Core messages to avoid scope confusion
lines.push("## Role Requirements (Core-Only)");
lines.push("");
lines.push("> **Note**: `client` role references `session.*` message types that are defined in `@nano-agent/nacp-session`, not in Core.");
lines.push("> They appear here because Core's state machine needs phase-transition awareness, but their body schemas live in the Session profile package.");
lines.push("");
lines.push("| role | must_produce | must_consume | note |");
lines.push("|---|---|---|---|");
for (const [role, req] of Object.entries(NACP_ROLE_REQUIREMENTS)) {
  const produce = [...req.producer].join(", ") || "—";
  const consume = [...req.consumer].join(", ") || "—";
  const hasSessionRefs = [...req.producer, ...req.consumer].some(mt => mt.startsWith("session."));
  const note = hasSessionRefs ? "⚠️ includes session-profile placeholders" : "";
  lines.push(`| \`${role}\` | ${produce} | ${consume} | ${note} |`);
}
lines.push("");

// ── Error Registry ──
lines.push("## Error Registry");
lines.push("");
lines.push("| code | category | retryable | message |");
lines.push("|---|---|---|---|");
for (const def of listErrorDefinitions()) {
  lines.push(`| \`${def.code}\` | ${def.category} | ${def.retryable ? "✅" : "—"} | ${def.message} |`);
}
lines.push("");

const outDir = join(__dirname, "..", "..", "..", "docs");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, "nacp-core-registry.md");
writeFileSync(outPath, lines.join("\n"));
console.log(`✅ Generated registry doc → ${outPath}`);
