import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { listErrorMetas, type ErrorMeta, type NacpErrorCategory } from "../src/error-registry.ts";

type ClientErrorCategory =
  | "auth.expired"
  | "quota.exceeded"
  | "runtime.error"
  | "request.error"
  | "validation.failed"
  | "security.denied"
  | "dependency.unavailable"
  | "conflict.state";

const SELF_DIR = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(SELF_DIR, "../src/error-registry-client/generated-data.ts");

function mapCategory(meta: ErrorMeta): ClientErrorCategory {
  const isAuthish =
    meta.code === "invalid-auth" ||
    meta.code === "invalid-authority" ||
    meta.code === "password-mismatch" ||
    meta.code === "identity-not-found" ||
    meta.code === "refresh-invalid" ||
    meta.code === "refresh-expired" ||
    meta.code === "refresh-revoked" ||
    meta.code === "invalid-wechat-code" ||
    meta.code === "NACP_HMAC_INVALID" ||
    meta.code === "NACP_TIMESTAMP_SKEW";

  switch (meta.category as NacpErrorCategory) {
    case "validation":
      if (meta.code === "invalid-input" || meta.code === "invalid-request" || meta.code === "invalid-meta") {
        return "validation.failed";
      }
      return "request.error";
    case "security":
      return isAuthish ? "auth.expired" : "security.denied";
    case "quota":
      return "quota.exceeded";
    case "transient":
    case "dependency":
      return "dependency.unavailable";
    case "permanent":
      return "runtime.error";
    case "conflict":
      return "conflict.state";
  }
}

const clientMeta = listErrorMetas().map((meta) => ({
  code: meta.code,
  category: mapCategory(meta),
  http_status: meta.http_status,
  retryable: meta.retryable,
}));

const text = [
  `// Auto-generated by packages/nacp-core/scripts/generate-error-registry-client-data.ts.`,
  `// DO NOT EDIT BY HAND.`,
  ``,
  `import type { ClientErrorMeta } from "./types.js";`,
  ``,
  `export const GENERATED_CLIENT_ERROR_META = ${JSON.stringify(clientMeta, null, 2)} as const satisfies readonly ClientErrorMeta[];`,
  ``,
].join("\n");

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, text, "utf8");
process.stdout.write(`[generate-error-registry-client-data] wrote ${OUT_PATH}\n`);
