/**
 * Generate a human-readable hook registry doc.
 *
 * Output: dist/hook-registry.md
 *
 * Lists the 8 canonical events with their blocking semantics, allowed
 * outcome fields, payload-schema reference and redaction hints. This is
 * the governance-team artefact backing the in-scope allowlist truth.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { HOOK_EVENT_CATALOG } from "../src/catalog.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "..", "dist");
mkdirSync(outDir, { recursive: true });

const lines: string[] = [];
lines.push("# Hook Registry — @nano-agent/hooks");
lines.push("");
lines.push("_This file is auto-generated by `scripts/gen-registry-doc.ts`._");
lines.push("");
lines.push("## 1. Event catalog");
lines.push("");
lines.push("| Event | Blocking | Allowed outcomes | Redaction hints | Payload schema |");
lines.push("|-------|----------|------------------|------------------|----------------|");
for (const [name, meta] of Object.entries(HOOK_EVENT_CATALOG)) {
  lines.push(
    `| \`${name}\` | ${meta.blocking ? "yes" : "no"} | ${meta.allowedOutcomes.map((o) => `\`${o}\``).join(", ")} | ${meta.redactionHints.length ? meta.redactionHints.map((h) => `\`${h}\``).join(", ") : "—"} | \`${meta.payloadSchema}\` |`,
  );
}
lines.push("");
lines.push("## 2. Source priority (lookup order)");
lines.push("");
lines.push("`platform-policy` > `session` > `skill`");
lines.push("");
lines.push("## 3. Runtime kinds");
lines.push("");
lines.push("- `local-ts` — trusted in-proc TypeScript handler");
lines.push("- `service-binding` — remote hook worker via NACP-Core (stub in v1)");
lines.push("");
lines.push("## 4. Limitations");
lines.push("");
lines.push("- `updatedInput` is only valid on `PreToolUse`.");
lines.push("- `stop` is only valid on `PostToolUseFailure`.");
lines.push("- Matchers: `exact` / `wildcard` / `toolName` only (no regex).");
lines.push("- Client is receive-only on `hook.broadcast` — clients cannot respond with a `HookOutcome`.");

const outPath = join(outDir, "hook-registry.md");
writeFileSync(outPath, lines.join("\n"));
console.log(`✅ Generated hook registry doc → ${outPath}`);
